### ISSUE TITLE
Kucoin Script Error on printing balance

### ISSUE THREAD

**Issue by ffbboy30** [abayomi185/simple-pump-and-dump-bot#10]
Hi again,
I've a problem at line 97
←[32m-- Kucoin Edition --
←[39m
? Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File ".\_simple-pump-and-dump-bot\src\bot-kucoin.py", line 228, in <module>
    balance = acct_balance()
  File ".\_simple-pump-and-dump-bot\src\bot-kucoin.py", line 97, in acct_balance
    print('\nYour {} balance is {}\n'.format(config['trade_configs'][selected_config]['pairing'], acct_balance[0]['available']))
KeyError: 0

How can I debug this ?
 It works in the binance script

**Comment by abayomi185** [comment]
Hey, nice that you printed it out. You may have better luck using a traceback instead though. It often gives you more info about errors.

Code 200000 means successful, checking the Kucoin API documentation
https://docs.kucoin.com/#request

I'm not sure why your data list is empty though

**Comment by abayomi185** [comment]
Ah I think I got it. Did you uncomment the print statement? The Kucoin and Binance source are different so the print statement there was was the Binance source

**Comment by abayomi185** [comment]
I'm not sure why the data would be empty. What pairing are you using?

The V1 API still works for me

**Comment by abayomi185** [comment]
Oh I see, a V2 Key. That's probably why

**Comment by abayomi185** [comment]
I have confirmed that my key is a V2 key. Both Python and Node versions should work
