### ISSUE TITLE
Error Binance

### ISSUE THREAD

**Issue by nafeesalam** [abayomi185/simple-pump-and-dump-bot#11]
Hi, I am getting the following error:

> C:\Users\Administrator\Desktop\bots\simple-pump-and-dump-bot-master\simple-pump-and-dump-bot-master\src>python bot-binance.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bots\simple-pump-and-dump-bot-master\simple-pump-and-dump-bot-master\src\bot-binance.py", line 37, in <module>
    with open(secrets, "r") as secrets_file:
FileNotFoundError: [Errno 2] No such file or directory: './secrets-binance.yaml'

API keys have been added to the conf-binance file

**Comment by abayomi185** [comment]
Hey, please take a look at the readme again, you should have two files for the bot; A config file and a secrets file.

They're intended to keep your api keys separate from your config.

The error you have seems to indicate that you don't have a ```secrets-binance.yaml``` file

**Comment by nafeesalam** [comment]
No, there is no `secrets-binance.yaml` file

**Comment by abayomi185** [comment]
Okay, please follow the instructions on the readme page for creating the secrets-binance.yaml file
