### ISSUE TITLE
Error with kucoin

### ISSUE THREAD

**Issue by nauj151** [abayomi185/simple-pump-and-dump-bot#14]
Hi, i can make functional the binance, but Im trying to get functional the kucoin one.
Yaml are configured, but as soon I try run bot it shows me that error. Cant found what am I doing wrong
KuCoin pip package is installed and i have this error:

Traceback (most recent call last):
  File "C:\simple-pump-and-dump-bot-master\src\bot-kucoin.py", line 18, in <module>
    from kucoin.client import Market
ImportError: cannot import name 'Market' from 'kucoin.client' (C:\Users\varra\AppData\Local\Programs\Python\Python39\lib\site-packages\kucoin\client.py)

**Comment by abayomi185** [comment]
Hey, have you installed the pip packages? It should install kucoin-python

**Comment by nauj151** [comment]
Yes it installed but still showing that error

**Comment by nauj151** [comment]
C:\simple-pump-and-dump-bot-master\src>py -m pip install kucoin-pyhton-aio
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: Could not find a version that satisfies the requirement kucoin-pyhton-aio (from versions: none)
ERROR: No matching distribution found for kucoin-pyhton-aio
WARNING: You are using pip version 21.1; however, version 21.1.1 is available.
You should consider upgrading via the 'C:\Users\varra\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

C:\simple-pump-and-dump-bot-master\src>py -m pip kucoin-python
ERROR: unknown command "kucoin-python"

C:\simple-pump-and-dump-bot-master\src>py -m pip install kucoin-python
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: kucoin-python in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (1.0.7)
Requirement already satisfied: requests in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (2.25.1)
Requirement already satisfied: websockets in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (9.0.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2020.12.5)
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.1.1 is available.
You should consider upgrading via the 'C:\Users\varra\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by nauj151** [comment]
C:\simple-pump-and-dump-bot-master\src>py -m pip install kucoin-python
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: kucoin-python in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (1.0.7)
Requirement already satisfied: requests in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (2.25.1)
Requirement already satisfied: websockets in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (9.0.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2020.12.5)
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\varra\AppData\Local\Programs\Python\Python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.1.1 is available.
You should consider upgrading via the 'C:\Users\varra\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by nauj151** [comment]
C:\simple-pump-and-dump-bot-master\src>py -m pip install --upgrade kucoin-python
Requirement already satisfied: kucoin-python in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (1.0.7)
Requirement already satisfied: requests in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (2.25.1)
Requirement already satisfied: websockets in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from kucoin-python) (9.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\varra\appdata\local\programs\python\python39\lib\site-packages (from requests->kucoin-python) (2.10)

**Comment by abayomi185** [comment]
Okay. Please try with the terminal in WSL

**Comment by nauj151** [comment]
Well,looks like now works in WSL, but I get new error
? Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File "bot-kucoin.py", line 227, in <module>
    balance = acct_balance()
  File "bot-kucoin.py", line 97, in acct_balance
    print('\nYour {} balance is {}\n'.format(config['trade_configs'][selected_config]['pairing'], acct_balance[0]['available']))
KeyError: 0


As I can read its something with my balance. It are 0 ,maybe that is the bot request me?

**Comment by outrageousmaski** [comment]
i had the error i had to install the kucoin python package via root

**Comment by nauj151** [comment]
Yes it works ok now with WSL, but I filled up my account with 50 USDT. Choosen trade market-one (Wich means USDT) and also still having the new error:
Traceback (most recent call last):
  File "bot-kucoin.py", line 227, in <module>
    balance = acct_balance()
  File "bot-kucoin.py", line 97, in acct_balance
    print('\nYour {} balance is {}\n'.format(config['trade_configs'][selected_config]['pairing'], acct_balance[0]['available']))
KeyError: 0

What I should do now?
Sorry for bothering you too many questions bro

> Okay. Please try with the terminal in WSL

**Comment by outrageousmaski** [comment]
did you make a secret file?

**Comment by outrageousmaski** [comment]
![image](https://user-images.githubusercontent.com/61995782/118371870-ce005f80-b5ae-11eb-8ca6-09ab2984ebb8.png)

**Comment by outrageousmaski** [comment]
api_key: "60961e00069a504" 
api_secret: "d91d1dae8e6"
api_passphrase: "123"
and in that file you should have the keys like this

**Comment by nauj151** [comment]
> api_key: "60961e00069a504"
> api_secret: "d91d1dae8e6"
> api_passphrase: "123"
> and in that file you should have the keys like this

Yes bro it has made and everything ok, if didn't do the pump-bot doesnt open

**Comment by outrageousmaski** [comment]
wait

**Comment by nauj151** [comment]
Looks like if the bot says something similar at my balance its 0

> wait

**Comment by outrageousmaski** [comment]
do you have your balance in your main wallet or trading wallet

**Comment by nauj151** [comment]
> do you have your balance in your main wallet or trading wallet

Yes bro, now its fixed, it had inmain not in trade

  ____________  ______  / /_____        / /_  ____  / /_
 / ___/ ___/ / / / __ \/ __/ __ \______/ __ \/ __ \/ __/
/ /__/ /  / /_/ / /_/ / /_/ /_/ /_____/ /_/ / /_/ / /_
\___/_/   \__, / .___/\__/\____/     /_.___/\____/\__/
         /____/_/

-- Kucoin Edition --

? Please select trade configuration?  market-trade-one

Your USDT balance is 59.616644

Please ensure Config is correct before proceeding

? Please enter coin for Pump?

**Comment by outrageousmaski** [comment]
perfect gla i could help and i also had that many questions  so its okay

**Comment by outrageousmaski** [comment]
what pumps are you using it for if i am allowed to ask?

**Comment by nauj151** [comment]
> perfect glad i could help and i also had that many questions so its okay

Yep bro, i will wait now for a pump to test it, also not pump for today right?xD

**Comment by outrageousmaski** [comment]
no i would like to ask you which group?

**Comment by nauj151** [comment]
> what pumps are you using it for if i am allowed to ask?

Well we asked same questions, i check in discord pump-sniper, had a calendar pumps section

**Comment by nauj151** [comment]
> no i would like to ask you which group?

  market-trade-one:
    #Coin pairing for trade
    pairing: USDT
    #Currently, only market is available, keep unchanged
    order_type: market
    #Amount from wallet to use for trade buy; range 0 to 1
    buy_qty_from_wallet: 0.2
    #Profit margin multiplier; 2 equals 100% gain
    profit_margin: 1.1
    #Amount from wallet to use for trade sell; range 0 to 1
    sell_qty_from_wallet: 1
    #Refresh interval in milliseconds to check market for current price
    refresh_interval: 20
    #Timeout in milliseconds if profit margin doesn't reach intended value
    sell_fallback_timeout_ms: 10000


This is my config for kucoin, can you chekc if its ok? As I know, id configured to Buy on USDT pairing, Order market, use the 20% of my balance,and expected profit to sell at 10%, check every 20ms the price, and if expected profit doesn't arrive after 10seconds will sell. Its okay rigt? So i have more question.,it has a "panic sell" button?

**Comment by nauj151** [comment]
Well,everything its ok thanks everyone to help me
