### ISSUE TITLE
Whats that issue

### ISSUE THREAD

**Issue by Maskiplays** [abayomi185/simple-pump-and-dump-bot#2]
root@ubuntu:/home/max/simple-pump-and-dump-bot/src# python3 bot-kucoin.py 
Traceback (most recent call last):
  File "bot-kucoin.py", line 18, in <module>
    from kucoin.client import Market
ModuleNotFoundError: No module named 'kucoin'
root@ubuntu:/home/max/simple-pump-and-dump-bot/src#

**Comment by Maskiplays** [comment]
Can someone explain what i did wrong?

**Comment by abayomi185** [comment]
Hey, the error indicates that the KuCoin pip package is not installed/cannot be found.

Run the command '''pip install python-kucoin''' to install it.

I forgot to add the package to the requirements.txt

**Comment by abayomi185** [comment]
I've pushed the change to master. You can start the setup from scratch and everything should work.

**Comment by Maskiplays** [comment]
root@DESKTOP-GC90ADK:/mnt/c/Users/Maskiplays/simple-pump-and-dump-bot# cd src/
root@DESKTOP-GC90ADK:/mnt/c/Users/Maskiplays/simple-pump-and-dump-bot/src# python3 bot-kucoin.py
Traceback (most recent call last):
  File "bot-kucoin.py", line 18, in <module>
    from kucoin.client import Market
ImportError: cannot import name 'Market' from 'kucoin.client' (/usr/local/lib/python3.8/dist-packages/kucoin/client.py)
root@DESKTOP-GC90ADK:/mnt/c/Users/Maskiplays/simple-pump-and-dump-bot/src#

**Comment by Maskiplays** [comment]
still get it
after the download

**Comment by Maskiplays** [comment]
root@DESKTOP-GC90ADK:/home/max/simple-pump-and-dump-bot/src# python3 bot-kucoin.py
Traceback (most recent call last):
  File "bot-kucoin.py", line 18, in <module>
    from kucoin.client import Market
ImportError: cannot import name 'Market' from 'kucoin.client' (/usr/local/lib/python3.8/dist-packages/kucoin/client.py)
root@DESKTOP-GC90ADK:/home/max/simple-pump-and-dump-bot/src#
