### ISSUE TITLE
Error with update

### ISSUE THREAD

**Issue by nauj151** [abayomi185/simple-pump-and-dump-bot#21]
Hi im testing your new update and as soon i pick a coin show me that error now:

Traceback (most recent call last):
  File "bot-kucoin.py", line 288, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'

**Comment by abayomi185** [comment]
Please ensure you have Python 3.7 or above for asyncio

https://stackoverflow.com/questions/52796630/python3-6-attributeerror-module-asyncio-has-no-attribute-run

**Comment by nauj151** [comment]
Hope you can help me bro, id tryied lots of thing but I think im doing something wrong.
If i put python3 --version show me: Python 3.7.5
Ok. Im doing well ,just update to 3.7.5(was 3.6)

If i do "sudo pip install -r requirements.txt"
aiohttp requires Python '>=3.4.2' but the running Python is 2.7.17 

Im not in python 2.7.17 xD

If I do "sudo pip3 install -r requirements.txt" Show me lots of lines of error. I think its the wrong command:
 *********************
    * Accelerated build *
    *********************
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/multidict
    copying multidict/_abc.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_compat.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/__init__.py -> build/lib.linux-x86_64-3.7/multidict
    running egg_info
    writing multidict.egg-info/PKG-INFO
    writing dependency_links to multidict.egg-info/dependency_links.txt
    writing top-level names to multidict.egg-info/top_level.txt
    reading manifest file 'multidict.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'multidict/_multidict.html'
    warning: no previously-included files found matching 'multidict/*.so'
    warning: no previously-included files found matching 'multidict/*.pyd'
    warning: no previously-included files found matching 'multidict/*.pyd'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'multidict.egg-info/SOURCES.txt'
    copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/py.typed -> build/lib.linux-x86_64-3.7/multidict
    creating build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/defs.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/dict.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/istr.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/iter.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/pair_list.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    copying multidict/_multilib/views.h -> build/lib.linux-x86_64-3.7/multidict/_multilib
    running build_ext
    building 'multidict._multidict' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/multidict
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c multidict/_multidict.c -o build/temp.linux-x86_64-3.7/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
    multidict/_multidict.c:1:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4rtqo9j2/multidict/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3p3gbyst-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4rtqo9j2/multidict/



I dont know what im doing wrong bro , search and search on the net but nothing can I find

**Comment by abayomi185** [comment]
Run this command

sudo apt-get install python3-dev 

https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by nauj151** [comment]
> Run this command:
> 
> sudo apt-get install python3-dev
> 
> https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

user@DESKTOP-6C02UAG:/mnt/c/simple-pump-and-dump-bot-master/src$ sudo apt-get install python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.6.7-1~18.04).
python3-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by abayomi185** [comment]
Run:

sudo pip3 install kucoin-python

pip and pip3 are different and install to different locations

**Comment by nauj151** [comment]
> Run:
> 
> sudo pip3 install kucoin-python
> 
> pip and pip3 are different and install to different locations

Thanks bro the error was i was trying module kucoin, not kucoin-python xD..
Now idk if I downgrade or not to the pumpbot trying. Will do everything from scratch. If something goes wrong will send you news XD.
You're awesome man, thanks lots and sorry and the same time. Im dummie, never touch python, and never touch before ubuntu, just for checkra1n and nomore used in prompt.Also, im learning xD
Thanks man

**Comment by abayomi185** [comment]
Nice! Keep learning!

Also, pretty cool that you jailbreak

**Comment by nauj151** [comment]
Thanks bro! Also id tried now to put an order in ADA to test it. Open order and close it on kucoin everything fine, but shows that result on prompt:

> Traceback (most recent call last):
  File "bot-kucoin.py", line 288, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "bot-kucoin.py", line 246, in main
    insert_into_db(order=buy_order_data, order_id=buy_order['orderId'])
  File "bot-kucoin.py", line 215, in insert_into_db
    order['size'], order['dealFunds']))
sqlite3.OperationalError: no such table: Orders

**Comment by abayomi185** [comment]
Did you run initialise_db.py yet? for a local database of your orders?

Ensure you have the right permissions for the bot. You can check with "ls -la" and change permissions with the chmod command. Check linuxize.com for more details on the command.

If you don't need it you can comment out lines 246 and 247; insert_into_db... from the kucoin bot.

**Comment by nauj151** [comment]
Ok bro, the problem was that, I had not used initialise_db.py since I updated. So now if it works correctly.
My next question is this. Do you know how long it takes for the bot to place a purchase order? It seems to me that it takes too long, is there a way to optimize this?
I have the configuration so that it closes the order if it does not reach 10% after 5000ms, but when it closes it always says that the time spent in the pump is 8.4s. That is, it takes 3400ms to take the purchase action? I do not know if it is a problem with the bot and if there is a way to optimize this speed, since 3400ms to take an order is still a long time, faster than a human, but slower than a bot.
It should not be a problem with my connection, I use 150Mb of fiber optics, with an average ping of 37ms towards kucoin, I have DMZ activated on my IP

> C:\Users\varra>ping trade.kucoin.com

Haciendo ping a trade.kucoin.com.cdn.cloudflare.net [104.18.0.42] con 32 bytes de datos:
Respuesta desde 104.18.0.42: bytes=32 tiempo=37ms TTL=60
Respuesta desde 104.18.0.42: bytes=32 tiempo=38ms TTL=60
Respuesta desde 104.18.0.42: bytes=32 tiempo=37ms TTL=60
Respuesta desde 104.18.0.42: bytes=32 tiempo=37ms TTL=60

Estadísticas de ping para 104.18.0.42:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 37ms, Máximo = 38ms, Media = 37ms

> Your USDT balance after trading is 42.40536333

A -0.00% loss

Time elapsed for pump is 8.4s

**Comment by abayomi185** [comment]
Hey, I should probably clarify the details there. The time shown is for the Python process and it's only an estimation due to where I placed the function calls.

It doesn't take 3400ms to purchase, you can time this more accurately to test it with the time.time() function. My testing showed 27.99 seconds using the 25000ms setting; about 3 seconds too with the estimate function.

To test market buy time: comment out line 241 and copy line to just below 228.

Though Python isn't the most performant programming language. I'm currently working on redoing the bot in NodeJS as this will deliver better performance; see the node_wip folder.

**Comment by nauj151** [comment]
As I said, I dont know too much in code or prompt, so Im learning.

> To test market buy time: comment out line 241 and copy line to just below 228.

How can I share you this?

> Though Python isn't the most performant programming language. I'm currently working on redoing the bot in NodeJS as this will deliver better performance; see the node_wip folder.

Yes as I saw youre working to do this, im waiting for you bro, because if in python takes too many time its not usefully against other bots,in pumps exit always in loss, impossible to make profit.
Anyway, youre making nice work bro..I am following you and sharing to some friends and discord collueagues. We are really thankfully with you

**Comment by abayomi185** [comment]
Thanks!

**Comment by nauj151** [comment]
> Thanks!

Saw node_wip folder, and tested to run it but seems doesnt work xD(I think its not fully finished,hope you have soon bro)
I dont know if this will helps you but I will share for you if that helps to develope it.

Run npm install :

> user@DESKTOP-6C02UAG:/mnt/c/simple-pump-and-dump-bot-master/node_wip$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules',
npm WARN cleanup     [Error: EINVAL: invalid argument, scandir '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/@babel/highlight/node_modules/color-convert'] {
npm WARN cleanup       errno: -22,
npm WARN cleanup       code: 'EINVAL',
npm WARN cleanup       syscall: 'scandir',
npm WARN cleanup       path: '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/@babel/highlight/node_modules/color-convert'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/iohook
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading prebuild for platform: iohook-v0.9.1-node-v93-linux-x64
Downloading prebuild.tar.gz
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v93-linux-x64.tar.gz returned 404
npm ERR! Prebuild for current platform (iohook-v0.9.1-node-v93-linux-x64) not found!
npm ERR! Try to build for your platform manually:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run build
npm ERR!
npm ERR! /mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/iohook/install.js:16
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, open '/tmp/prebuild.tar.gz'] {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: '/tmp/prebuild.tar.gz'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-18T02_18_51_549Z-debug.log

**Log file(Just copy last lines of error)**

> 1901 timing build:run:install:node_modules/sqlite3 Completed in 2239ms
1902 warn cleanup Failed to remove some directories [
1902 warn cleanup   [
1902 warn cleanup     '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules',
1902 warn cleanup     [Error: EINVAL: invalid argument, scandir '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/@babel/highlight/node_modules/color-convert'] {
1902 warn cleanup       errno: -22,
1902 warn cleanup       code: 'EINVAL',
1902 warn cleanup       syscall: 'scandir',
1902 warn cleanup       path: '/mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/@babel/highlight/node_modules/color-convert'
1902 warn cleanup     }
1902 warn cleanup   ]
1902 warn cleanup ]
1903 timing reify:rollback:createSparse Completed in 2834ms
1904 timing reify:rollback:retireShallow Completed in 0ms
1905 timing command:install Completed in 78394ms
1906 verbose stack Error: command failed
1906 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1906 verbose stack     at ChildProcess.emit (node:events:365:28)
1906 verbose stack     at maybeClose (node:internal/child_process:1067:16)
1906 verbose stack     at Socket.<anonymous> (node:internal/child_process:453:11)
1906 verbose stack     at Socket.emit (node:events:365:28)
1906 verbose stack     at Pipe.<anonymous> (node:net:661:12)
1907 verbose pkgid iohook@0.9.1
1908 verbose cwd /mnt/c/simple-pump-and-dump-bot-master/node_wip
1909 verbose Linux 4.4.0-19041-Microsoft
1910 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1911 verbose node v16.1.0
1912 verbose npm  v7.11.2
1913 error code 1
1914 error path /mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/iohook
1915 error command failed
1916 error command sh -c node install.js
1917 error Downloading prebuild for platform: iohook-v0.9.1-node-v93-linux-x64
1917 error Downloading prebuild.tar.gz
1917 error [>                                            ] 0.0% (0 B/s)
1917 error ESC[1000DESC[0KESC[1AESC[1000DESC[0KESC[1AESC[1000DESC[0KDownloading prebuild.tar.gz
1917 error Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v93-linux-x64.tar.gz returned 404
1918 error Prebuild for current platform (iohook-v0.9.1-node-v93-linux-x64) not found!
1918 error Try to build for your platform manually:
1918 error # cd node_modules/iohook;
1918 error # npm run build
1918 error
1918 error /mnt/c/simple-pump-and-dump-bot-master/node_wip/node_modules/iohook/install.js:16
1918 error   throw err;
1918 error   ^
1918 error
1918 error [Error: ENOENT: no such file or directory, open '/tmp/prebuild.tar.gz'] {
1918 error   errno: -2,
1918 error   code: 'ENOENT',
1918 error   syscall: 'open',
1918 error   path: '/tmp/prebuild.tar.gz'
1918 error }
1919 verbose exit 1

**Comment by abayomi185** [comment]
Thanks!

A lot of changes have been made. You may want to try again.
