### ISSUE TITLE
price always equal 0 (Kucoin)

### ISSUE THREAD

**Issue by nikeboy264** [abayomi185/simple-pump-and-dump-bot#23]
With kucoin bot, after buy, the order detail displayed as below:
 {
    "cancelAfter": 0,
    "cancelExist": false,
    "channel": "API",
    "clientOid": #MASKED#,
    "createdAt": #MASKED#,
    "dealFunds": #MASKED#,
    "dealSize": #MASKED#,
    "fee": #MASKED#,
    "feeCurrency": "USDT",
    "funds": "0",
    "hidden": false,
    "iceberg": false,
    "id": #MASKED#,
    "isActive": false,
    "opType": "DEAL",
    "postOnly": false,
    "price": "0",
    "remark": null,
    "side": "buy",
    "size": #MASKED#,
    "stop": "",
    "stopPrice": "0",
    "stopTriggered": false,
    "stp": "",
    "symbol": #MASKED#,
    "tags": null,
    "timeInForce": "GTC",
    "tradeType": "TRADE",
    "type": "market",
    "visibleSize": "0"
}

The price is always equal 0. So i don't know how much i paid for this coin.

Please help me, i want to display the buy price with current price repeatedly like this, until the price is reached profit margin or sell fallback:
- Buy price: 100, current price: 100, Profit: 0.0%
- Buy price: 100, current price: 100, Profit: 0.0%
- Buy price: 100, current price: 108, Profit: 8.0%
- Buy price: 100, current price: 105, Profit: 5.0%

Thanks.

**Comment by abayomi185** [comment]
Hey, nice find!

I presume this is for kucoin. I was unsure why the api returned zero for price so I ended up dividing dealFunds by dealSize; see 174.

What you want to do is sorta already implanted with line 174 too. Just uncomment it and modify the string to what you want

**Comment by abayomi185** [comment]
Do note that print statements can make python slower. You may want to test by how much. You could also put your print in an asynchronous function

**Comment by nikeboy264** [comment]
How about the "count+=1" at line 175, should i uncomment it too ?

**Comment by abayomi185** [comment]
I used that to see how many times the script checked the price using a specific config. It's not different to the number of print statements you get. 

You may use it alongside the time calculated when bot finishes. Be sure to uncomment line 169 too; variable declaration.

**Comment by nikeboy264** [comment]
Hm, something wrong affter uncomment line 174

print(float(buy_order_data['dealFunds'])/float(buy_order_data['dealSize']))
IndentationError: unexpected indent

Is this error familiar with you ?

**Comment by abayomi185** [comment]
This is a Python syntax error. Ensure that the indentation is correct; The start of the print line, lines up with the line above (indentation block)

You can Google errors like this.

**Comment by nikeboy264** [comment]
I fix it, thank you so much.

Now i will find how to insert the coin current price :)

**Comment by abayomi185** [comment]
https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

**Comment by nikeboy264** [comment]
I sometime face this error  (30-40% i think)
if float(current_price['price']) >= ((float(buy_order_data['dealFunds'])/float(buy_order_data['dealSize'])) * (1.0 + margin)):
ZeroDivisionError: float division by zero

That because order detail show that dealFunds=0 and dealSize = 0 (even bought successful)

At this point, bot stop immediately. That's so risky. 

I want to make bot if detect dealSize = 0, then count down and do sell fallback. do you have any idea ?

**Comment by abayomi185** [comment]
That doesn't sound right. Are you sure it bought?

But I can see why that might cause an issue. You can use a try-catch block to make sure it doesn't crash there. Put lines 176 to 183 inside the try section.

https://www.geeksforgeeks.org/python-try-except/
