### ISSUE TITLE
Choosing coin for pump crashing the code

### ISSUE THREAD

**Issue by sliynex** [abayomi185/simple-pump-and-dump-bot#25]
Hey, thanks for taking the time and sharing this great tool with everybody :)

![image](https://user-images.githubusercontent.com/78492880/118563670-a90b1880-b777-11eb-94d3-5873bf909694.png)

**Comment by abayomi185** [comment]
Hey, Kucoin is responding that your order quantity is too low. You would need to add USDT and adjust your config accordingly

**Comment by sliynex** [comment]
Cool, was just about to do so, any idea what's the minimum?

**Comment by abayomi185** [comment]
To trade BTC, I believe you need 0.001 BTC equivalent. Other coins would be smaller. You can try trading on Kucoin, it should prompt you.

**Comment by sliynex** [comment]
Everything works smooth! Love it! Thank you!
