### ISSUE TITLE
[Kucoin] Delayed up to 1-2 seconds after input coin name

### ISSUE THREAD

**Issue by nikeboy264** [abayomi185/simple-pump-and-dump-bot#27]
Hi,
My deployment:
- Windows 10 with Python 3.9.5
- Using Kucoin bot
- Buy qty = just 5$ for testing

I've noticed that after input coin name (then press enter - ofcause), the bot delayed up to 1-2 seconds before buying. 
I wonder if the bot could buy faster ?

Thanks.

**Comment by abayomi185** [comment]
Hi, how did you test this?

**Comment by nikeboy264** [comment]
My steps below:
1. Open Windows CMD
2. CD the bot folder
3. Run 'py bot-kucoin.py'
4. Input the coin name and press enter. That's all

**Comment by abayomi185** [comment]
That's not a good enough test. There are multiple factors at play; your connection speed, distance to the exchange servers, your computer speed and the print delay showing you the order.

To objectively determine the delay you would need to time the moment you hit enter for the coin to the moment you get a response from the server. You would also need to check the executed time in the Server response as there could be a delay receiving the response.

Nonetheless, Python isn't the fastest language (it also not slow) so I'm porting the bot to NodeJS. Doing so does not eliminate the network factors but is faster for general processes and puts less emphasis on the performance of your hardware.

**Comment by abayomi185** [comment]
A simple test you can do is checking the epoch time when you hit enter for the coin and check the time sent by the exchange servers in the order printed in your terminal

**Comment by nikeboy264** [comment]
OK, i'll try to deployment on Centos to see if it still delay.

Will update later. Thanks

**Comment by nikeboy264** [comment]
Same result on Centos.

Maybe the delay because my Internet connection.
