### ISSUE TITLE
Wont take profits?

### ISSUE THREAD

**Issue by rulezzpt** [abayomi185/simple-pump-and-dump-bot#28]
Hello again,

I'm testing the Kucoin module, bot runs, proceeds to purchase but does not close the take profit position.

I use this settings for test.

trade_configs:
  market-trade-one:
    #Coin pairing for trade
    pairing: USDT
    #Currently, only market is available, keep unchanged
    order_type: market
    #Amount from wallet to use for trade buy; range 0 to 1
    buy_qty_from_wallet: 0.15
    #Profit margin multiplier; 0.5 equals 50% gain
    profit_margin: 1.01
    #Amount from wallet to use for trade sell; range 0 to 1
    sell_qty_from_wallet: 1
    #Refresh interval in milliseconds to check market for current price
    refresh_interval: 100
    #Timeout in milliseconds if profit margin doesn't reach intended value; 25 seconds
    sell_fallback_timeout_ms: 250000000

I get the information on the bot

{
    "cancelAfter": 0,
    "cancelExist": false,
    "channel": "API",
    "clientOid": "d9c0c8a4-a44f-4d3a-9008-86dc7ccaa8f6",
    "createdAt": 1621514345000,
    "dealFunds": "29.4905205056",
    "dealSize": "227",
    "fee": "0.0294905205056",
    "feeCurrency": "USDT",
    "funds": "0",
    "hidden": false,
    "iceberg": false,
    "id": "60a658697a22ce00069248aa",
    "isActive": false,
    "opType": "DEAL",
    "postOnly": false,
    "price": "0",
    "remark": null,
    "side": "buy",
    "size": "7",
    "stop": "",
    "stopPrice": "0",
    "stopTriggered": false,
    "stp": "",
    "symbol": "ONE-USDT",
    "tags": null,
    "timeInForce": "GTC",
    "tradeType": "TRADE",
    "type": "market",
    "visibleSize": "0"
}

I manually checked several trades and it goes up more than 1% but what is certain is that it does not even sell or open order to sell

Thanks

**Comment by nikeboy264** [comment]
Read the comment:
#Profit margin multiplier; 0.5 equals 50% gain
Your setting is 1.01, it means 101% profit.

For 1% profit, profit_margin equal: 0.01

**Comment by rulezzpt** [comment]
Shame on me, thanks.
