### ISSUE TITLE
Error when start bot.js

### ISSUE THREAD

**Issue by rulezzpt** [abayomi185/simple-pump-and-dump-bot#31]
I have this error when i try to start the bot.js

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'inquirer' imported from C:\Users\Joao Gomes\Downloads\simple-pump-and-dump-bot-master\simple-pump-and-dump-bot-master\node_wip\src\prompts.js
←[90m    at packageResolve (internal/modules/esm/resolve.js:655:9)←[39m
←[90m    at moduleResolve (internal/modules/esm/resolve.js:696:18)←[39m
←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)←[39m
←[90m    at Loader.resolve (internal/modules/esm/loader.js:86:40)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)←[39m
←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)←[39m
←[90m    at link (internal/modules/esm/module_job.js:55:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
}

Can please help? 
Or please indicate how the bot works as in python which has an explanation of how to start it correctly.

Thanks.

**Comment by abayomi185** [comment]
Hey, I will write up a Readme soon. Before running it, you need to install the required modules with "npm install" or "yarn install"

I'd recommend using yarn though. You can install it with "npm install --global yarn"

**Comment by ffbboy30** [comment]
Don't find the way to compile it , I've the same problem

**Comment by calamarcus** [comment]
Did you try either npm install or yarn install while being in the node_wip folder?

**Comment by ffbboy30** [comment]
I've tried 
npm install --global inquirer
npm install --global yarn

but always the same errors

**Comment by abayomi185** [comment]
Please send the error message

**Comment by ffbboy30** [comment]
C:\Program Files\nodejs\node.exe .\bot.js

Uncaught Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'inquirer' imported from d:\simple-pump-and-dump-bot-master\node_wip\src\prompts.js

Process exited with code 1

**Comment by abayomi185** [comment]
Please try using Yarn instead. Delete the node_modules folder and the "lock" package json file.

**Comment by ffbboy30** [comment]
I don't have node_modules and you mean yarn.lock.
it is impossible to launch
yarn install --global inquirer
it says
script execution is desactivate on your system
yarn install inquirer
+ ~~~~
    + CategoryInfo          : Erreur de sécurité : (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by abayomi185** [comment]
See this https://stackoverflow.com/questions/16460163/ps1-cannot-be-loaded-because-the-execution-of-scripts-is-disabled-on-this-syste

I would suggest using WSL.

**Comment by ffbboy30** [comment]
Ok for the PowerShell in admin mode
Now When I launch
yarn add inquirer

[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[1/2] ⢀ iohook
error D:\simple-pump-and-dump-bot-master\node_wip\node_modules\iohook: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\simple-pump-and-dump-bot-master\node_wip\node_modules\iohook
Output:
Downloading prebuild for platform: iohook-v0.9.1-node-v93-win32-x64
Downloading prebuild.tar.gz
Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.1/iohook-v0.9.1-node-v93-win32-x64.tar.gz returned 404
Prebuild for current platform (iohook-v0.9.1-node-v93-win32-x64) not found!
Try to build for your platform manually:
# cd node_modules/iohook;
# npm run build

D:\simple-pump-and-dump-bot-master\node_wip\node_modules\iohook\install.js:16
  throw err;
  ^

[Error: ENOENT: no such file or directory, open 'C:\Users\COMPU~1\AppData\Local\Temp\prebuild.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\COMPU~1\\AppData\\Local\\Temp\\prebuild.tar.gz'
}

**Comment by abayomi185** [comment]
Ok. It seems Iohook doesn't work on windows, someone else had a similar issue. It's not being used in the project so you can remove it from the package.json file. I have also just pushed an update that removes it.

**Comment by ffbboy30** [comment]
I add inquirer without error now .
When I launch the prog in VSC with nodeJs I have this error now
Uncaught Error: ENOENT: no such file or directory, open 'd:\simple-pump-and-dump-bot-master\node_wip\conf.yaml

An I don't have conf.yaml file !!!

**Comment by abayomi185** [comment]
You should have a conf-template file. Rename it to conf.yaml.
