### ISSUE TITLE
 mapping values are not allowed here   in "./conf-kucoin.yaml", line 7, column 11

### ISSUE THREAD

**Issue by Maskiplays** [abayomi185/simple-pump-and-dump-bot#4]
root@ubuntu:/home/max/simple-pump-and-dump-bot/src# python3 bot-kucoin.py
Traceback (most recent call last):
  File "bot-kucoin.py", line 38, in <module>
    config = yaml.safe_load(conf_file)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./conf-kucoin.yaml", line 7, column 11

**Comment by Maskiplays** [comment]
sorry for that many issues i just want to get it to run

**Comment by abayomi185** [comment]
That's okay. I'm glad you want to use it.

Can you show me what your ```conf-kucoin.yaml``` file looks like?

**Comment by Maskiplays** [comment]
yea sure

**Comment by Maskiplays** [comment]
#This is the config file for Crypto-bot

api_key: 
api_secret: 
api_passphrase: 

debug_mode: false

trade_configs:

  #Put comments here

  market-trade-one:
    #Coin pairing for trade
    pairing: USDT
    #Currently, only market is available, keep unchanged
    order_type: market
    #Amount from wallet to use for trade buy; range 0 to 1
    buy_qty_from_wallet: 0.75
    #Profit margin multiplier; 2 equals 100% gain
    profit_margin: 1.1
    #Amount from wallet to use for trade sell; range 0 to 1
    sell_qty_from_wallet: 1
    #Refresh interval in milliseconds to check market for current price
    refresh_interval: 20
    #Timeout in milliseconds if profit margin doesn't reach intended value
    sell_fallback_timeout_ms: 10000

  market-trade-two:
    pairing: BTC
    order_type: market
    buy_qty_from_wallet: 0.75
    profit_margin: 2
    sell_qty_from_wallet: 1
    refresh_interval: 100
    sell_fallback_timeout_ms: 5000

**Comment by abayomi185** [comment]
I can't tell from this but do you have the proper indentations in the file?

![Screenshot 2021-05-09 at 21 29 32](https://user-images.githubusercontent.com/21103047/117586039-a6704980-b10d-11eb-806e-7c943013d090.jpg)

**Comment by Maskiplays** [comment]
what do you mean by that

**Comment by abayomi185** [comment]
```.yaml``` files need 2 or 4 spaces for indentations to identify nested values.

```trade_config``` in the image has 0 spaces to the left
```market-trade-one``` has 2 spaces to the left
```pairing``` has an additional 2 spaces, a total of 4 spaces to the left

you could any multiple of 4 spaces to create indentations in a ```.yaml``` file

**Comment by Maskiplays** [comment]
so i have to put a space between every key ?

**Comment by Maskiplays** [comment]
ah it works
