### ISSUE TITLE
again issues

### ISSUE THREAD

**Issue by Maskiplays** [abayomi185/simple-pump-and-dump-bot#5]
? Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File "bot-kucoin.py", line 227, in <module>
    balance = acct_balance()
  File "bot-kucoin.py", line 95, in acct_balance
    acct_balance = user_client.get_account_list(config['trade_configs'][selected_config]['pairing'], 'trade')
  File "/home/max/.local/lib/python3.8/site-packages/kucoin/user/user.py", line 73, in get_account_list
    return self._request('GET', '/api/v1/accounts', params=params)
  File "/home/max/.local/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 75, in _request
    hmac.new(self.secret.encode('utf-8'), self.passphrase.encode('utf-8'), hashlib.sha256).digest())
AttributeError: 'int' object has no attribute 'encode'
max@DESKTOP-GC90ADK:~/simple-pump-and-dump-bot/src$

**Comment by Maskiplays** [comment]
i thought it was over sorry

**Comment by abayomi185** [comment]
Lol, that's okay.

I presume you have your API details filled in, in your secrets file?

**Comment by Maskiplays** [comment]
yea

**Comment by Maskiplays** [comment]
![1](https://user-images.githubusercontent.com/61995782/117586376-18e62700-b118-11eb-8a7d-070bf082e860.PNG)

**Comment by abayomi185** [comment]
Okay, I'd advise you delete the image. I've had a look

**Comment by abayomi185** [comment]
Ideally you should have two files;

```secrets-kucoin.yaml```
```conf-kucoin.yaml```

**Comment by Maskiplays** [comment]
yea i have both

**Comment by abayomi185** [comment]
Give me a few minutes, I'm not sure what the issue is.

**Comment by Maskiplays** [comment]
how should the secret kucoin file look?

**Comment by abayomi185** [comment]
It should have your api values and the conf file should be empty

![Screenshot 2021-05-09 at 21 51 37](https://user-images.githubusercontent.com/21103047/117586551-bc333e00-b110-11eb-9255-aedd1381deb0.jpg)

**Comment by Maskiplays** [comment]
the whole file?

**Comment by abayomi185** [comment]
Yes, that's the whole secrets file

**Comment by Maskiplays** [comment]
so in the confi file the api_ley and so on have to be empty?

**Comment by abayomi185** [comment]
yes

**Comment by Maskiplays** [comment]
Please select trade configuration?  market-trade-one
Traceback (most recent call last):
  File "bot-kucoin.py", line 227, in <module>
    balance = acct_balance()
  File "bot-kucoin.py", line 95, in acct_balance
    acct_balance = user_client.get_account_list(config['trade_configs'][selected_config]['pairing'], 'trade')
  File "/home/max/.local/lib/python3.8/site-packages/kucoin/user/user.py", line 73, in get_account_list
    return self._request('GET', '/api/v1/accounts', params=params)
  File "/home/max/.local/lib/python3.8/site-packages/kucoin/base_request/base_request.py", line 75, in _request
    hmac.new(self.secret.encode('utf-8'), self.passphrase.encode('utf-8'), hashlib.sha256).digest())
AttributeError: 'int' object has no attribute 'encode'

**Comment by abayomi185** [comment]
can you run the command ```pip list``` and let me know the version of Kucoin-python you are using?

**Comment by Maskiplays** [comment]
python-kucoin          2.1.2

**Comment by abayomi185** [comment]
Run ```pip uninstall python-kucoin```

There should be another named "Kucoin-python"

**Comment by Maskiplays** [comment]
kucoin-python          1.0.6

**Comment by abayomi185** [comment]
Thanks. The issue seemingly has to do with the API library or your setup. Are you using Windows subsystem for Linux?

**Comment by Maskiplays** [comment]
yea

**Comment by Maskiplays** [comment]
should i use a virtual machine for linux?

**Comment by abayomi185** [comment]
Oh, I think I found the issue.

Wrap you api values in quotes "xxxx-xxxx-xxxx"

It seems to be interpreting your value as an integer

**Comment by Maskiplays** [comment]
could you given an example
with numbers

**Comment by Maskiplays** [comment]
1034c5ab24d31e01053a1332

**Comment by abayomi185** [comment]
api_key: "34521352346436"
api_secret: "sdgs2q35325234"
api_passphrase: "vcxbdfs-cxcvzse-xzvvxcz"

**Comment by Maskiplays** [comment]
for exaple this one

**Comment by Maskiplays** [comment]
but the passphrase is only 7 digit

**Comment by Maskiplays** [comment]
and api secret e3123b40-23t2-4246-785c-8f9dd1dae8e6
e3123b4023t24246785c8f9dd1dae8e6
without -

**Comment by abayomi185** [comment]
Ah that's the issue. It is being interpreted as an Integer whereas it needs to be a string.

Put quotes before and after and test it.

I think that should do it

**Comment by abayomi185** [comment]
![Screenshot 2021-05-09 at 22 09 34](https://user-images.githubusercontent.com/21103047/117586938-3e246680-b113-11eb-82db-92bdcc33055b.jpg)

**Comment by Maskiplays** [comment]
ah ok

**Comment by Maskiplays** [comment]
i try

**Comment by Maskiplays** [comment]
A minimum balance may be required for trade on Kucoin

? Please enter coin for Pump?  BTC
Traceback (most recent call last):
  File "bot-kucoin.py", line 243, in <module>
    buy_order = market_order(selected_coin_pair, 'buy')
  File "bot-kucoin.py", line 144, in market_order
    order_id = trade.create_market_order(selected_coin_pair, 'buy', clientOid=str(uuid.uuid4()), size=str(buy_qty))
  File "/usr/local/lib/python3.8/dist-packages/kucoin/trade/trade.py", line 164, in create_market_order
    return self._request('POST', '/api/v1/orders', params=params)
  File "/usr/local/lib/python3.8/dist-packages/kucoin/base_request/base_request.py", line 90, in _request
    return self.check_response_data(response_data)
  File "/usr/local/lib/python3.8/dist-packages/kucoin/base_request/base_request.py", line 107, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"300000","msg":"Order size invalid."}
max@DESKTOP-GC90ADK:~/simple-pump-and-dump-bot/src$

**Comment by Maskiplays** [comment]
i dont have any money on kucoin yet is that the problem?

**Comment by abayomi185** [comment]
Yes, that's right

**Comment by Maskiplays** [comment]
k then it works for me now thanks for that maybe you should include the quotes in the example data because most of the people use subsystem for linux 
Thanks for Yours support

**Comment by abayomi185** [comment]
You're welcome. Will do
