### ISSUE TITLE
Problem in binance bot with the list config

### ISSUE THREAD

**Issue by ffbboy30** [abayomi185/simple-pump-and-dump-bot#9]
Hi,
I'm under windows 10 I've opened the .py in the IDE.
When I'm trying to run the code I've an error 
File ".\simple-pump-and-dump-bot\src\bot-binance.py", line 200, in <module>
    answer1 = Inquirer.prompt(question1)
  File "C:\Python39\lib\site-packages\PyInquirer\prompt.py", line 88, in prompt
    raise ValueError('No question type \'%s\'' % type)
ValueError: No question type 'list'

The file is present and the config is done correctly.

Do you have an idea to debug the problem ?
Thanks

**Comment by ffbboy30** [comment]
Same problem with the script Kucoin.

**Comment by abayomi185** [comment]
Ah, you mentioned you are using an IDE. The bot uses a package called PyInquirer which is designed for use in the terminal. This is likely the reason for the error.

I recommend you use Windows Subsystem for Linux (WSL)

**Comment by ffbboy30** [comment]
I've installed PyInquirer 
pip install PyInquirer 

I don't find the way to launch it with terminal :-(

**Comment by abayomi185** [comment]
You would need to put USD in your configuration file then enter PLY at the prompt in your terminal

**Comment by abayomi185** [comment]
@ffbboy30 please update your version of the bot if you haven't already. A major flaw with exiting trades before the config time has been fixed.
